### ISSUE TITLE
Text not visible when selecting country in Ionic 6 with Angular 17 (Modular Version)

### ISSUE THREAD

**Issue by fox-alvarez** [aymericl/ion-intl-tel#1]
![Captura de pantalla 2024-11-06 173313](https://github.com/user-attachments/assets/f56d79fe-1091-4852-966e-71701df07fc1)

When selecting a country in my Ionic 6 app (Angular 17, modular version), the country text is not visible because opacity: 0 is applied to it.

**Steps to Reproduce:**
1. Use the country selection component (IonSelect or similar).
2. Select a country.
3. Notice the country name text is invisible due to opacity: 0.

**Expected Behavior:**
The selected country text should be visible.

**Actual Behavior:**
The text is not visible due to opacity: 0 in the styles.

**Ionic & Angular Versions:**
Ionic: 6.x.x
Angular: 17.x.x

Thanks for the modular implementation in Ionic 6 and Angular 17!

**Comment by aymericl** [comment]
Can you test with the previous release like 2.3.1 ? 
The last version uses the new ionic templating and may cause your problem.

**Comment by fox-alvarez** [comment]
Perfect! Installing version 2.3.1 worked. Thank you @aymericl!
